# Bob has left. George is now the service technician; Henry and Ida are new.
user.alice=administrator
user.cecilia=power_user
user.david=ordinary_user
user.erica=ordinary_user
user.fred=ordinary_user
user.george=service_technician
user.henry=ordinary_user
user.ida=power_user

role.ordinary_user=print,queue
role.power_user=topQueue,restart
role.service_technician=start,stop,restart,status,readConfig,setConfig
role.administrator=

inherits.power_user=ordinary_user
inherits.administrator=service_technician,power_user
